FROM dronehippie/base:arm

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Git" \
  org.opencontainers.image.vendor="Webhippie" \
  org.opencontainers.image.documentation="https://dronehippie.github.io/git/"

ENTRYPOINT ["/bin/drone-git"]
ADD bin/drone-git /bin/
